export enum ActionTypes {
  LOADING = "LOADING",
  ERROR = "ERROR",
  CHANGE_LANGUAGE = "CHANGE_LANGUAGE",
  FETCHED_REPOS = "FETCHED_REPOS",
  OPEN_START_MENU = "OPEN_START_MENU",
  OPEN_FOLDER = "OPEN_FOLDER",
  CLOSE_FOLDER = "CLOSE_FOLDER",
  OPEN_ALERT = "OPEN_ALERT",
  CLOSE_ALERT = "CLOSE_ALERT",
  SET_ACTIVE_WINDOW = "SET_ACTIVE_WINDOW"
}
